CC = cc 
CFLAGS = -std=c99 -Wall -ggdb -O0 -lm
LDFLAGS = 

main: 
	$(CC) -o popcorn.exe popcorn.c $(CFLAGS) $(LDFLAGS)
main3: 
	$(CC) -o threadbrot.exe threadbrot.c $(CFLAGS) $(LDFLAGS)
main1: 
	$(CC) -o fbrot.exe fbrot.c $(CFLAGS) $(LDFLAGS)
main2: 
	$(CC) -o mandel.exe mandelbrot.c $(CFLAGS) $(LDFLAGS)
